org: stephane71
app: api
service: places-api

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3
  memorySize: 128

functions:
  get:
    handler: services/get/index.handler
    events:
      - http:
          path: /{slug}
          method: get
          cors: true
          request:
            parameters:
              paths:
                slug: true
