service: place-api

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: eu-west-2
  memorySize: 128

  environment:
    TABLE_REGION: eu-west-3
    TABLE_NAME: Places-test
    ACCESS_KEY_ID: ${ssm:/dev/aws/la-foulee-api/access_key_id~true}
    SECRECT_ACCESS_KEY: ${ssm:/dev/aws/la-foulee-api/secret_access_key~true}

  iamManagedPolicies:
    - arn:aws:iam::514894570076:policy/La-Foulee-Places-${self:provider.stage}

functions:
  get:
    handler: places/get.handler
    events:
      - http:
          path: /{slug}
          method: get
          authorizer: aws_iam
          cors: true
          request:
            parameters:
              paths:
                slug: true
  insert:
    handler: places/insert.handler
    events:
      - http:
          path: /
          method: post
          authorizer: aws_iam
          cors: true
